import { Zap, ArrowLeft, FileText } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";

const TermsPage = () => (
  <div className="min-h-screen bg-background">
    <header className="bg-primary text-primary-foreground py-8">
      <div className="container mx-auto px-4">
        <Link to="/" className="inline-flex items-center gap-2 text-sm opacity-80 hover:opacity-100 mb-4">
          <ArrowLeft className="w-4 h-4" /> Back to Calculator
        </Link>
        <div className="flex items-center gap-3 mb-4">
          <div className="bg-accent text-accent-foreground p-2 rounded-lg">
            <FileText className="w-6 h-6" />
          </div>
          <h1 className="text-3xl md:text-4xl font-extrabold">Terms of Service</h1>
        </div>
        <p className="text-sm opacity-70">Last updated: March 8, 2026</p>
      </div>
    </header>

    <main className="container mx-auto px-4 py-12 max-w-3xl">
      <p className="text-muted-foreground leading-relaxed text-base mb-8">
        Please read these Terms of Service ("Terms") carefully before using BillMeter, a free electricity bill calculator operated by Lade Stack ("we", "our", "us"). By accessing or using BillMeter, you agree to be bound by these Terms.
      </p>

      <h2 className="text-xl font-bold mt-8 mb-3">1. Acceptance of Terms</h2>
      <p className="text-muted-foreground leading-relaxed">
        By accessing BillMeter at ladestack.in/billmeter or any associated URL, you acknowledge that you have read, understood, and agree to these Terms of Service. If you do not agree with any part of these terms, you should not use the Tool.
      </p>

      <h2 className="text-xl font-bold mt-8 mb-3">2. Description of Service</h2>
      <p className="text-muted-foreground leading-relaxed">
        BillMeter is a free, web-based electricity bill estimation tool that:
      </p>
      <ul className="space-y-1 text-muted-foreground mt-2">
        <li>• Calculates estimated electricity bills based on user-provided inputs (state, units consumed, connected load)</li>
        <li>• Provides slab-wise bill breakdowns for residential consumers across 10+ Indian states</li>
        <li>• Offers an appliance-based unit consumption estimator</li>
        <li>• Displays state-wise tariff comparison data</li>
        <li>• Provides electricity saving tips and FAQ information</li>
      </ul>

      <h2 className="text-xl font-bold mt-8 mb-3">3. Estimates Disclaimer</h2>
      <p className="text-muted-foreground leading-relaxed">
        <strong>BillMeter provides estimates only, not exact bill amounts.</strong> The results generated by this tool are approximate calculations based on publicly available tariff data from State Electricity Regulatory Commissions (SERCs) and Distribution Companies (DISCOMs).
      </p>
      <p className="text-muted-foreground leading-relaxed mt-2">
        Your actual electricity bill may differ from BillMeter estimates due to:
      </p>
      <ul className="space-y-1 text-muted-foreground mt-2">
        <li>• Meter rent and service charges</li>
        <li>• Regulatory surcharges not included in our calculations</li>
        <li>• Wheeling and transmission charges</li>
        <li>• Special subsidies (BPL, farmer, SC/ST exemptions)</li>
        <li>• Mid-year tariff revisions by SERCs</li>
        <li>• Billing cycle differences (your bill may cover more or fewer than 30 days)</li>
        <li>• Power factor penalties or incentives</li>
        <li>• Arrears, adjustments, or credits from previous billing periods</li>
      </ul>
      <p className="text-muted-foreground leading-relaxed mt-3">
        <strong>Always verify your bill with your state DISCOM for official and exact amounts.</strong> BillMeter should not be used as a substitute for official bill verification.
      </p>

      <h2 className="text-xl font-bold mt-8 mb-3">4. No Affiliation</h2>
      <p className="text-muted-foreground leading-relaxed">
        BillMeter and Lade Stack are <strong>not affiliated with, endorsed by, or connected to</strong> any of the following entities:
      </p>
      <ul className="space-y-1 text-muted-foreground mt-2">
        <li>• MSEDCL (Maharashtra State Electricity Distribution Company Ltd.)</li>
        <li>• MERC (Maharashtra Electricity Regulatory Commission)</li>
        <li>• BSES Rajdhani / BSES Yamuna / TPDDL (Delhi DISCOMs)</li>
        <li>• BESCOM, UGVCL, UPPCL, TNEB, TSSPDCL, WBSEDCL, JVVNL, MPCZ, or any other DISCOM</li>
        <li>• Any State Electricity Regulatory Commission (SERC)</li>
        <li>• Any central or state government body</li>
        <li>• Ministry of Power, Government of India</li>
      </ul>
      <p className="text-muted-foreground leading-relaxed mt-2">
        All DISCOM names, logos, and tariff data used are the property of their respective organizations and are used here solely for informational purposes.
      </p>

      <h2 className="text-xl font-bold mt-8 mb-3">5. Free Service</h2>
      <p className="text-muted-foreground leading-relaxed">
        BillMeter is provided completely free of charge. We do not charge any fees, require subscriptions, or offer premium tiers. There are no hidden costs. The service is funded and maintained by Lade Stack as a public utility tool.
      </p>

      <h2 className="text-xl font-bold mt-8 mb-3">6. No Warranty</h2>
      <p className="text-muted-foreground leading-relaxed">
        BillMeter is provided "AS IS" and "AS AVAILABLE" without warranties of any kind, whether express or implied, including but not limited to:
      </p>
      <ul className="space-y-1 text-muted-foreground mt-2">
        <li>• Accuracy or completeness of tariff data</li>
        <li>• Fitness for a particular purpose</li>
        <li>• Uninterrupted or error-free operation</li>
        <li>• Timeliness of tariff updates</li>
      </ul>

      <h2 className="text-xl font-bold mt-8 mb-3">7. Limitation of Liability</h2>
      <p className="text-muted-foreground leading-relaxed">
        In no event shall Lade Stack, its founders, employees, or contributors be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from:
      </p>
      <ul className="space-y-1 text-muted-foreground mt-2">
        <li>• Use of or inability to use BillMeter</li>
        <li>• Any inaccuracy in bill estimates</li>
        <li>• Financial decisions made based on BillMeter results</li>
        <li>• Any errors or omissions in tariff data</li>
        <li>• Service interruptions or downtime</li>
      </ul>

      <h2 className="text-xl font-bold mt-8 mb-3">8. Acceptable Use</h2>
      <p className="text-muted-foreground leading-relaxed">You agree not to:</p>
      <ul className="space-y-1 text-muted-foreground mt-2">
        <li>• Use BillMeter for any unlawful purpose</li>
        <li>• Attempt to reverse engineer, decompile, or extract the source code</li>
        <li>• Use automated tools to scrape data at excessive rates</li>
        <li>• Misrepresent BillMeter results as official DISCOM calculations</li>
        <li>• Use BillMeter to mislead consumers or businesses</li>
      </ul>

      <h2 className="text-xl font-bold mt-8 mb-3">9. Intellectual Property</h2>
      <p className="text-muted-foreground leading-relaxed">
        The BillMeter name, design, code, and content are the intellectual property of Lade Stack. Tariff data is sourced from public government documents and is not claimed as proprietary. You may share BillMeter results for personal use but may not reproduce the tool or its content for commercial purposes without written permission.
      </p>

      <h2 className="text-xl font-bold mt-8 mb-3">10. Tariff Data Updates</h2>
      <p className="text-muted-foreground leading-relaxed">
        We strive to update tariff data within 30 days of new SERC notifications. However, we do not guarantee real-time accuracy. Tariff data currently reflects the FY 2025–26 tariff orders as published by respective SERCs. Users should verify current rates with their DISCOM, especially after April 1 each year when new tariff orders typically take effect.
      </p>

      <h2 className="text-xl font-bold mt-8 mb-3">11. Modifications to Terms</h2>
      <p className="text-muted-foreground leading-relaxed">
        We reserve the right to modify these Terms at any time. Changes will be effective immediately upon posting on this page. Your continued use of BillMeter after changes constitutes acceptance of the modified Terms. We recommend reviewing this page periodically.
      </p>

      <h2 className="text-xl font-bold mt-8 mb-3">12. Governing Law</h2>
      <p className="text-muted-foreground leading-relaxed">
        These Terms shall be governed by and construed in accordance with the laws of India. Any disputes arising from the use of BillMeter shall be subject to the exclusive jurisdiction of the courts in Solapur, Maharashtra, India.
      </p>

      <h2 className="text-xl font-bold mt-8 mb-3">13. Contact</h2>
      <p className="text-muted-foreground leading-relaxed">
        For questions regarding these Terms of Service, please contact:
      </p>
      <ul className="space-y-1 text-muted-foreground mt-2">
        <li>• <strong>Email:</strong> legal@ladestack.in</li>
        <li>• <strong>Website:</strong> <a href="https://ladestack.in" target="_blank" rel="noopener noreferrer" className="text-accent underline">ladestack.in</a></li>
        <li>• <strong>Address:</strong> Lade Stack, Solapur, Maharashtra 413001, India</li>
      </ul>

      <div className="text-center mt-12">
        <Link to="/">
          <Button className="bg-accent text-accent-foreground hover:bg-accent/90 text-lg px-8 py-6 rounded-xl font-semibold gap-2">
            <Zap className="w-5 h-5" /> Back to Calculator →
          </Button>
        </Link>
      </div>
    </main>

    <footer className="bg-primary text-primary-foreground py-6 mt-12">
      <div className="container mx-auto px-4 text-center text-sm opacity-70">
        <p>© 2026 Lade Stack — <a href="https://ladestack.in" className="underline">ladestack.in</a></p>
      </div>
    </footer>
  </div>
);

export default TermsPage;
